### ISSUE TITLE
Jupyter Notebook example?

### ISSUE THREAD

**Issue by Jackal08** [sdepy/sdepy#17]
Hi Team, 

Interesting project you have built here. I would like to make use of it to determine optimal trading rules without backtesting by using synthetic data. 

Do you maybe have an example of using an Ornstein Uhlenbeck process to generate synthetic data?

**Comment by m-cip** [comment]
Sorry for coming back to this just now... a new release is in the making with a jupyter notebook as a quick guide, that should be out in a few days - hope it is helpful.
