### ISSUE TITLE
Use a default_rng() instance instead of random.normal

### ISSUE THREAD

**Issue by andreas-wolf** [sdepy/sdepy#33]
Feature request:
wiener source is using np.random.normal and np.random.multivariate_normal.

Both need np.random.seed(SEED) to be set for tests or repeatable experiments.
random.seed is known to not work as expected in multithreaded environments (some test frameworks, REST-Implementations).
Numpy strongly recommends to use an instance of a random number generator instead:
https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html?highlight=random%20normal#numpy.random.normal

I'd like to have the opportunity to pass a random generator as optional parameter to the class which is then used as random source.

**Comment by andreas-wolf** [comment]
I forgot to mention (from the numpy docs):
By default, Generator uses bits provided by PCG64 which has better statistical properties than the legacy MT19937 used in RandomState.

So this feature request may affect numerical reproducibility with previous versions of the code. As a workaround one could pass the older MT19937 bit generator  as rng (which is not recommended):

```
from numpy.random import Generator, MT19937
rng = Generator(MT19937(12345))
```

**Comment by m-cip** [comment]
Thanks for pointing this out, indeed an update to the new numpy BitGnerator/Generator framework is long overdue... Do expect to have it soon in the master branch, and as part of the next release in a couple of months
