### ISSUE TITLE
Model Parameterisation / Calibration

### ISSUE THREAD

**Issue by gregz0012** [sdepy/sdepy#34]
It would be useful to get the developers thoughts on appropriate techniques to approximate the parameters for these models. From reviewing the code and documentation I cannot see any in-built calibration functions.

My interest is specific to the Ornstein Uhlenbeck process and the approximation of k, mu, and sigma. However, I suspect that others would be interested in examples for other processes.

**Comment by m-cip** [comment]
The approach to parameter calibration depends on the phenomena the SDEs are intended to model, with techniques very specific to each domain of application (physics? finance?): the whole subject, deemed too big to cover in decent generality, was kept beyond the scope of sdepy.

In general, a problem entails parameter-dependent observables computed as the output of a montecarlo simulation: if all else fails (i.e., if the problem at hand does not allow for some other domain-specific shortcut), a grid search on the parameter space is one possibility to consider. Integrating an SDE on a grid of parameters is easily done in sdepy, an example is found in the quickguide; unfortunately, in the subject matter of calibration this is as far as it goes, sorry about that...
